### ISSUE TITLE
No Proteus Option in Tools Menu after enabling Plugin

### ISSUE THREAD

**Issue by kharelpankaj** [flipkart-incubator/android-studio-proteus-plugin#2]
I just Installed and enabled the plugin. I restarted the Android studio. But no luck. When in layout xml, I didn't find the Proteus option under tools section .
 Android Studio Version 3.1.2

**Comment by adityasharat** [comment]
@kharelpankaj It has been a while since we updated the plugin. Please consider the plugin deprecated as it is anyway not compatible with the new version of proteus.
